package com.pasindu.nursingotapp.ai

data class NursingAiContext(val route:String,val screenTitle:String,val purpose:String,val facts:List<String> = emptyList(),val calculations:List<String> = emptyList(),val safetyRules:List<String> = emptyList(),val availableActions:List<String> = emptyList()) {
    fun asPromptContext():String=buildString {
        appendLine("CURRENT SCREEN: $screenTitle")
        appendLine("ROUTE: $route")
        appendLine("PURPOSE: $purpose")
        if(facts.isNotEmpty()){appendLine("FACTS:");facts.forEach{appendLine("- $it")}}
        if(calculations.isNotEmpty()){appendLine("AUTHORITATIVE CALCULATIONS:");calculations.forEach{appendLine("- $it")}}
        if(safetyRules.isNotEmpty()){appendLine("SAFETY/LIMITATIONS:");safetyRules.forEach{appendLine("- $it")}}
        if(availableActions.isNotEmpty()){appendLine("AVAILABLE APP ACTIONS:");availableActions.forEach{appendLine("- $it")}}
    }
}

fun nursingAiContextForRoute(route:String?):NursingAiContext?=when(route){
"home"->NursingAiContext("home","Home dashboard","Summarize saved work, finance and wellness information",listOf("Dashboard values summarize information supplied by underlying app modules.","Changing saved duty, finance or wellness inputs can change dashboard summaries."),availableActions=listOf("Open Work","Open Finance","Open Clinical","Open More"))
"claim_period"->NursingAiContext("claim_period","Claims and duty periods","Group saved duty entries into a claim period",listOf("Selected start and end dates define the claim period.","OT and PH/DO summaries originate from saved duty records."),listOf("OT and payment values use the deterministic calculation layer."),listOf("Verify dates, duty type, time entries and applicable rates before submitting a claim."),listOf("Open Daily Entry","Open Finance","Open Smart Insights"))
"analytics"->NursingAiContext("analytics","Smart Insights","Visualize work and claim patterns for the selected period",listOf("SHIFTS means recorded duty entries in the selected analytics period.","AVG OT / CLAIM includes displayed claim periods, including zero-OT claims.","MONTH identifies the selected calendar period."),listOf("AVG OT / CLAIM = total OT hours across displayed claim periods ÷ number of displayed claim periods."),availableActions=listOf("Open Claims","Open Work"))
"advanced_finance_hub"->NursingAiContext("advanced_finance_hub","Advanced Finance Hub","Present a transparent financial summary from saved profile, compensation and claim data",calculations=listOf("OT amount = total OT hours × configured OT rate.","PH amount = PH days × PH rate.","DO amount = DO days × DO rate.","Gross = basic salary + risk allowance + CLA allowance + additional allowances + OT + PH + DO.","Estimated net = gross earnings − listed paysheet deductions.","36-hour workload visual = normal-duty hours ÷ 36, capped at 100% for display."),safetyRules=listOf("Financial figures depend on saved inputs; the official paysheet is the final payment reference."),availableActions=listOf("Open Claim Period","Open Pay Sheet Bank","Open Profile"))
"clinical_calculators"->NursingAiContext("clinical_calculators","Clinical Calculators","Provide deterministic nursing calculation tools",facts=listOf("Tools include dosage, infusion, pediatric, ICU, emergency and unit-conversion workflows."),calculations=listOf("Each calculator uses its programmed deterministic formula and displayed inputs."),safetyRules=listOf("Confirm units and patient-specific inputs.","Do not use AI as a replacement for an order, local protocol, independent check or clinical judgement."))
"nurse_command_center"->NursingAiContext("nurse_command_center","Nurse Command Center","Organize existing workload and wellness signals into useful next actions",facts=listOf("Command Center can surface existing duty, workload, wellness and app-state information."),safetyRules=listOf("Scores are supportive signals, not diagnoses or clinical risk determinations."),availableActions=listOf("Open Care Pulse","Open Work","Open Smart Insights"))
"care_pulse"->NursingAiContext("care_pulse","Care Pulse","Summarize app-derived workload and recovery-related wellness signals",facts=listOf("The pulse is derived from available app information and helps notice change over time."),safetyRules=listOf("Wellness scores are not medical measurements and must not be used to diagnose burnout or illness."),availableActions=listOf("Open Command Center","Review Workload"))
"more_tools"->NursingAiContext("more_tools","More Tools","Keep supporting workspaces discoverable without overcrowding primary navigation",facts=listOf("Supporting areas include Command Center, Care Pulse, Smart Insights, Knowledge/CPD, Clinical Planning, Pay Sheet Bank and Profile."))
"knowledge_hub"->NursingAiContext("knowledge_hub","Knowledge and CPD","Support learning, reference and professional-development activity",facts=listOf("CPD progress represents activity recorded in the app and does not by itself prove external accreditation."),safetyRules=listOf("Check source, date and local policy when a resource affects clinical practice."))
"clinical_planning"->NursingAiContext("clinical_planning","Clinical Planning","Organize structured clinical planning information and next actions",safetyRules=listOf("Review patient-specific information and applicable local protocols before acting on a plan."))
"pay_sheet_bank"->NursingAiContext("pay_sheet_bank","Pay Sheet Bank","Retrieve saved payment and paysheet records",facts=listOf("Saved documents are references and do not silently replace source claim calculations."),safetyRules=listOf("Use the official paysheet as the final payment reference when figures differ."))
"profile"->NursingAiContext("profile","Nursing Profile","Provide identity, work and compensation inputs used by connected modules",facts=listOf("Changing source profile values can change downstream claim and finance summaries."),safetyRules=listOf("Review affected claim and finance values after changing important source data."))
"daily_entry"->NursingAiContext("daily_entry","Daily Entry","Record source duty information used by OT, claim and finance summaries",facts=listOf("Dates, normal duty, PH/DO, leave and OT time entries are recorded here."),safetyRules=listOf("Verify the actual duty record and applicable policy before submitting a claim."),availableActions=listOf("Open Claims","Open Finance"))
else->null}
