package com.pasindu.nursingotapp.ui.clinicalai

/** Lightweight on-device intent router. No clinical dose is generated by this class. */
object ClinicalAiRouter {
    private data class Route(
        val id: String,
        val title: String,
        val keywords: Set<String>
    )

    private val routes: List<Route> = listOf(
        Route("emergency", "Emergency Calculators", setOf("arrest", "cpr", "anaphylaxis", "adrenaline", "epinephrine", "shock", "rsi", "resuscitation", "හදිසි", "ඇනෆිලැක්සිස්")),
        Route("icu", "ICU Critical Care", setOf("icu", "vasoactive", "noradrenaline", "norepinephrine", "dopamine", "dobutamine", "sedation", "electrolyte", "potassium", "kcl", "map", "svr", "parkland", "burn")),
        Route("dosage", "Advanced Dosage", setOf("dose", "dosage", "dilution", "reconstitution", "percentage", "dextrose", "vial", "ampoule", "drug")),
        Route("iv", "IV Drip Sync", setOf("iv", "drip", "gtt", "drops", "drop", "gravity", "pump", "infusion")),
        Route("high", "High-Alert Specials", setOf("insulin", "heparin", "pca", "glucose", "sugar", "cbg", "aptt", "sliding")),
        Route("weight", "Weight & Infusions", setOf("weight", "mg/kg", "mcg/kg/min", "continuous", "rate", "infusion")),
        Route("convert", "Unit Conversions", setOf("convert", "conversion", "meq", "mcg", "mg", "gram", "volume", "unit")),
        Route("bsa", "BSA & Chemo", setOf("bsa", "body", "surface", "mosteller", "chemo", "chemotherapy", "oncology")),
        Route("pediatric", "Paediatric Rules", setOf("pediatric", "paediatric", "child", "baby", "infant", "clark", "young", "fried", "ළමා"))
    )

    fun suggest(query: String): ClinicalAiSuggestion? {
        val text = query.trim().lowercase()
        if (text.isBlank()) return null

        val tokens: List<String> = Regex("[^\\p{L}\\p{N}/+]+").split(text)
            .filter { token: String -> token.isNotBlank() }

        var bestRoute: Route? = null
        var bestScore = 0

        for (route: Route in routes) {
            var routeScore = 0
            for (token: String in tokens) {
                routeScore += when {
                    route.id == "iv" && token == "iv" -> 8
                    route.keywords.any { keyword: String -> keyword.equals(token, ignoreCase = true) } -> 6
                    route.keywords.any { keyword: String -> keyword.contains(token, ignoreCase = true) } -> 3
                    else -> 0
                }
            }
            if (routeScore > bestScore) {
                bestScore = routeScore
                bestRoute = route
            }
        }

        if (bestScore <= 0 || bestRoute == null) {
            return ClinicalAiSuggestion(
                title = "No verified in-app match",
                message = "I could not map this request to a built-in clinical engine. Use a verified clinical reference rather than inventing a calculation.",
                severity = AiSeverity.CHECK
            )
        }

        return ClinicalAiSuggestion(
            title = "Suggested tool: ${bestRoute.title}",
            message = "AI routing only. Open the deterministic calculator and verify the indication, units, patient data, preparation, and local protocol.",
            severity = when (bestRoute.id) {
                "emergency", "high", "icu" -> AiSeverity.HIGH_ALERT
                else -> AiSeverity.INFO
            },
            actions = listOf(bestRoute.id)
        )
    }
}
